Update dependencies
- ci: build with go-1.17.2

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,13 +6,23 @@ jobs:
     steps:
       - checkout
       - run:
-          name: "Update Go"
+          name: "Install Go"
           command: |
-            sudo rm -rf /usr/local/go
-            wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
-            sudo tar -xvf go1.12.7.linux-amd64.tar.gz
-            sudo mv go /usr/local
-            rm go1.12.7.linux-amd64.tar.gz
+            # taken from https://golang.org/dl/, will need to be updated on version bump
+            sha256_linux_amd64='f242a9db6a0ad1846de7b6d94d507915d14062660616a61ef7c808a76e4f1676'
+            filename="go1.17.2.linux-amd64.tar.gz"
+            pushd /tmp
+            hash="$(curl -fL "https://golang.org/dl/${filename}" | tee "${filename}" | sha256sum | cut -f 1 -d ' ')"
+            [ "${sha256_linux_amd64}" = "${hash}" ] || (echo "${filename} has an invalid hash ${hash}" >&2 ; exit 1)
+            rm -rf /var/tmp/go &> /dev/null
+            tar -xpf "${filename}" -C /var/tmp/.
+            echo 'export GOROOT=/var/tmp/go' >> $BASH_ENV
+            echo "export PATH=/var/tmp/go/bin:$PATH" >> $BASH_ENV
+            popd
+      - run:
+          name: "Go version"
+          command: |
+            go version
       - run:
           name: "Install Vault CLI"
           command: |
